apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: cindergold-delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
