apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invenio-files-claim
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: manilabronze
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
